# Stock CLI 配置文件示例
# 请复制此文件为 settings.yaml 并修改相应配置

# LLM 设置
llm:
  # 当前使用的提供商 (openai/deepseek/ollama)
  provider: "openai"
  
  # OpenAI 配置
  openai:
    api_key: "your-openai-api-key"  # 请替换为您的API密钥
    base_url: "https://api.openai.com/v1"
    model: "gpt-4o-mini"
    timeout: 120

  # DeepSeek 配置
  deepseek:
    api_key: "your-deepseek-api-key"  # 请替换为您的API密钥
    base_url: "https://api.deepseek.com/v1"
    model: "deepseek-chat"
    timeout: 120

  # Ollama 本地配置
  ollama:
    api_key: "ollama"  # 本地服务使用固定值
    base_url: "http://localhost:11434/v1"
    model: "llama3.1"
    timeout: 120

  chatglm:
    api_key: "sk-xxxx"
    base_url: "https://open.bigmodel.cn/api/paas/v4/"
    model: "glm-4.5"
    timeout: 120

# Redis 配置
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  prefix: "stock_cli"

# 会话配置
session:
  default_session: "default"
  persist: true
  max_history: 50

# RAG 配置
rag:
  # 向量数据库路径
  vector_store_path: "data/db/rag_vector_store"
  # 集合名称
  collection_name: "stock_rag"
  # Ollama嵌入模型配置
  ollama:
    base_url: "http://localhost:11434"
    model: "nomic-embed-text"
  # 检索结果数量
  top_k: 5