# 触发器配置文件

# 定时触发器 (Time-based Triggers)
scheduled_tasks:
  
  # 每日市场概览
  - name: "daily_market_overview"
    description: "获取今日市场宏观新闻并进行总结"
    cron: "0 8 * * 1-5"  # 工作日早上8点
    enabled: true
    priority: 1
    task_template: "获取今日中国A股和美股市场的重要新闻，进行总结分析"
  
  # 每日关注股票监控
  - name: "daily_watchlist_check"
    description: "检查关注列表中股票的表现"
    cron: "0 9 * * 1-5"  # 工作日早上9点
    enabled: true
    priority: 2
    task_template: "检查我的关注股票列表中所有股票昨日和今日的表现，重点关注涨跌幅超过5%的股票"
  
  # 美股盘后总结
  - name: "us_market_after_hours"
    description: "美股收盘后市场总结"
    cron: "0 5 * * 2-6"  # 美股收盘后 (北京时间早上5点)
    enabled: true
    priority: 1
    task_template: "总结美股昨夜的整体表现，重点关注科技股和中概股"
  
  # 周末深度分析
  - name: "weekend_deep_analysis"
    description: "周末进行深度市场分析"
    cron: "0 10 * * 6"  # 周六上午10点
    enabled: false
    priority: 3
    task_template: "进行本周股市的深度分析，包括重大新闻事件对市场的影响，以及下周展望"

# 事件触发器 (Event-based Triggers)
event_triggers:
  
  # 股价异动监控
  price_alerts:
    - name: "large_price_movement"
      description: "股价大幅波动预警"
      enabled: true
      priority: 1
      conditions:
        # 1小时内涨跌幅超过5%
        price_change_1h: 5.0  # 百分比
        # 或者日内涨跌幅超过8%
        price_change_1d: 8.0
      watchlist: "user_watchlist"  # 监控用户关注列表
      check_interval: 300  # 检查间隔 (秒)
      task_template: "股票 {symbol} 在 {timeframe} 内{direction}了 {change_percent:.1f}%，请调查原因并分析影响"
  
  # 成交量异动
  volume_alerts:
    - name: "unusual_volume"
      description: "成交量异常预警" 
      enabled: true
      priority: 2
      conditions:
        volume_multiplier: 3.0  # 成交量是平均值的3倍以上
        min_volume: 1000000  # 最小成交量门槛
      watchlist: "user_watchlist"
      check_interval: 600  # 10分钟检查一次
      task_template: "股票 {symbol} 出现异常成交量 ({volume} vs 平均 {avg_volume})，请分析可能的原因"
  
  # 新闻事件触发
  news_triggers:
    - name: "breaking_financial_news"
      description: "重大财经新闻事件"
      enabled: false  # 需要新闻API支持
      priority: 1
      keywords:
        - "重大重组"
        - "并购"
        - "财报"
        - "业绩预告"
        - "监管"
        - "政策"
      check_interval: 1800  # 30分钟检查一次
      task_template: "发现重要新闻: {news_title}，请分析对相关股票和市场的潜在影响"

# 用户关注股票列表 (可以动态修改)
user_watchlist:
  stocks:
    # A股
    - symbol: "000001.SZ"  # 平安银行
      name: "平安银行"
      market: "A股"
    - symbol: "000858.SZ"  # 五粮液
      name: "五粮液" 
      market: "A股"
    - symbol: "600519.SH"  # 茅台
      name: "贵州茅台"
      market: "A股"
    
    # 美股
    - symbol: "AAPL"  # 苹果
      name: "Apple Inc."
      market: "US"
    - symbol: "NVDA"  # 英伟达
      name: "NVIDIA Corporation"
      market: "US"
    - symbol: "TSLA"  # 特斯拉
      name: "Tesla Inc."
      market: "US"
    
    # 港股
    - symbol: "00700.HK"  # 腾讯
      name: "腾讯控股"
      market: "HK"

# 触发器全局设置
global_settings:
  max_concurrent_tasks: 3  # 最大并发任务数
  task_timeout: 1800  # 任务超时时间 (30分钟)
  retry_failed_tasks: true
  retry_delay: 300  # 重试延迟 (5分钟)
  max_retries: 2
  
  # 工作时间限制 (只在这些时间内触发事件监控)
  working_hours:
    enabled: true
    start: "09:00"  # 北京时间
    end: "21:00"   # 北京时间
    timezone: "Asia/Shanghai"
  
  # 节假日跳过
  skip_holidays:
    enabled: true
    holiday_calendar: "china"  # 中国节假日
