# 触发器配置（配置驱动，解耦 session 与 trigger 逻辑）
# 用法：
#   uv run stock-cli trigger
#   - 若存在本文件且未提供 --fire/--interval，将自动并发运行此处配置的触发器
#   - 可显式：uv run stock-cli trigger --run-config
#   - 单独临时一次性触发：uv run stock-cli trigger --fire "xxx" -i 30 -s default -r system_scheduler
#
# 可扩展：
# - 在 src/stock_cli/triggers/ 下新增模块并使用 @register("type_name") 注册
# - 在此文件中将某条条目 type 设置为对应的 type_name 即可
#
# 下面示例：每 30 秒向模型询问当前北京时间（无限循环）
triggers:
  - name: every_30s_time
    enabled: true
    session_id: default            # 绑定的会话；仅通过 ID 解耦
    role: system_scheduler         # 事件在会话历史中的角色
    type: ask_time                 # 触发器类型（由 src/stock_cli/triggers/ask_time.py 注册）
    fire: "定时: 询问当前时间"        # 事件文本（记录到 session.append_event）
    task_template: "请直观回答当前北京时间，格式：YYYY-MM-DD HH:mm:ss。回答过程中必须调用工具获得实时信息"  # 提交给 kernel.run 的任务描述
    interval_seconds: 30           # 轮询间隔秒
    max_runs: 0                    # 0 表示无限
