# Stock Agent 触发器独立配置示例
# 使用 --triggers 指定该文件路径，例如：
#   uv run stock-cli trigger --session-id default --triggers ./config/triggers.example.yaml
# 入口不负责定时/轮询策略，具体参数通过 params 传入各自触发器，由触发器内部解释

triggers:
  # 示例一：定时询问时间（ask_time）
  - name: "ask-time-every-15s"
    type: "ask_time"      # 触发器类型，需与 src/stock_cli/triggers/ 下实现对应
    enabled: true
    params:
      interval_seconds: 15 # 由 ask_time 触发器解释的定时间隔（秒）

  # 你可以在此追加更多触发器
  # - name: "another-trigger"
  #   type: "xxx"
  #   enabled: true
  #   params:
  #     key1: value1
  #     key2: value2