# Stock Agent 触发器独立配置示例
# 使用 --triggers 指定该文件路径，例如：
#   uv run stock-cli trigger --session-id default --triggers ./config/triggers.example.yaml
# 入口不负责定时/轮询策略，具体参数通过 params 传入各自触发器，由触发器内部解释

triggers:
  

  # 示例二：会话收件箱（被动监听来自其他会话的通信）
  - name: "session-inbox"
    type: "session_inbox"  # 基于消息总线的被动触发，会监听该 session 的收件箱频道
    enabled: true
    params: {}             # 无需参数

  # 你可以在此追加更多触发器
  # - name: "another-trigger"
  #   type: "xxx"
  #   enabled: true
  #   params:
  #     key1: value1
  #     key2: value2